apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app-depl
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      # volumes:
      # - name: shared-logs
      #   persistentVolumeClaim:
      #     claimName: logs-pong-claim
      containers:
        - name: ping-pong-app
          image: skinatro/ping-pong-app:latest
          env:
            - name: PORT
              value: "5000"
          # volumeMounts:
          #   - name: shared-logs
              # mountPath: /tmp/kube