apiVersion: v1
kind: Pod
metadata:
  name: debug-net
  namespace: exercises
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    command: ["sleep", "3600"]
  restartPolicy: Never
