apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-07-15T17:23:14Z"
  generation: 2
  labels:
    app: todo-app
  name: todo-app
  namespace: default
  resourceVersion: "52156"
  uid: 4db7c240-05bc-461b-9379-484b90e34ee7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-15T22:58:13+05:30"
      creationTimestamp: null
      labels:
        app: todo-app
    spec:
      containers:
      - image: skinatro/todo-app
        imagePullPolicy: Always
        name: todo-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-15T17:26:21Z"
    lastUpdateTime: "2025-07-15T17:26:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-15T17:23:14Z"
    lastUpdateTime: "2025-07-15T17:28:16Z"
    message: ReplicaSet "todo-app-747cbd5fbd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
