apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2025-07-10T11:17:14Z"
  generation: 3
  labels:
    app: log-output
  name: log-output
  namespace: default
  resourceVersion: "1464"
  uid: 12df88bb-b58b-40ed-8988-d46d9f46e56f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: log-output
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-10T17:06:08+05:30"
      creationTimestamp: null
      labels:
        app: log-output
    spec:
      containers:
      - image: skinatro/log_output
        imagePullPolicy: Always
        name: log-output-pnzlr
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-10T11:26:49Z"
    lastUpdateTime: "2025-07-10T11:26:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-10T11:17:14Z"
    lastUpdateTime: "2025-07-10T11:36:30Z"
    message: ReplicaSet "log-output-788bc7cb57" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
