apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: logs-pong-claim
      containers:
        - name: log-output-read
          image: skinatro/log-output-read:latest
          env:
            - name: PORT 
              value: "5000"
          volumeMounts:
            - name: shared-logs
              mountPath: /tmp/kube
        - name: log-output-gen
          image: skinatro/log-output-gen:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /tmp/kube